name: huluxia_signin
on:
  schedule:    # 定时触发，UTC16点=北京时间次日0点
    - cron: '0 16 * * *'
  workflow_dispatch:  # 手动触发
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: '初始化python环境'
        uses: actions/setup-python@v4
        with:
           python-version: 3.10.11
      - name: '安装依赖'
        run: |
          pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: '开始运行'
        id: signin-outputs
        env:
          NOTIFIER_TYPE: ${{ secrets.NOTIFIER_TYPE }} 
          WECHAT_ROBOT_URL: ${{ secrets.WECHAT_ROBOT_URL }} # 取消注释启用企业微信机器人
          ACCOUNTS: ${{ secrets.ACCOUNTS }}
        run: |
          python ./main.py
